name: demo_webrtc
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.9.18
  wakelock: ^0.6.2
  json_annotation: ^4.7.0
  injectable: ^2.1.0
  get_it: ^7.2.0
  freezed_annotation: ^2.2.0
  flutter_bloc: ^8.1.1

  sdp_transform: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.2
  build_runner: ^2.3.3
  injectable_generator: ^2.1.3
  json_serializable: ^6.5.4
  freezed: ^2.3.2

flutter:
  uses-material-design: true
